CREATE DATABASE linfoapp DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

CREATE TABLE system(
    idSystem INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Hostname VARCHAR(22) NOT NULL,
    Processes INT UNSIGNED NOT NULL,
	Threads INT UNSIGNED NOT NULL,
    SystemLoad VARCHAR(22) NOT NULL,
    Uptime VARCHAR(22) NOT NULL,
	SystemDate datetime NOT NULL,
    PRIMARY KEY(idSystem)
);

CREATE TABLE cpuinfo(
    idCPUINFO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Model VARCHAR(22) NOT NULL,
    MHz INT UNSIGNED NOT NULL,
    UsagePercentage INT UNSIGNED NOT NULL,
	CPUDate DATETIME NOT NULL,
	PRIMARY KEY(idCPUINFO)
);

CREATE TABLE ram(
    idRAM INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Total VARCHAR(22) NOT NULL,
    Free BIGINT UNSIGNED NOT NULL,
    RAMDate DATETIME NOT NULL,
    PRIMARY KEY(idRAM)
);

CREATE TABLE networkDevices(
    idNetworkDevices INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(22) NOT NULL,
    ReceivedBytes VARCHAR(22) NOT NULL,
    SentBytes VARCHAR(22) NOT NULL,
    Status VARCHAR(22) NOT NULL,
    DeviceType VARCHAR(22) NOT NULL,
	NetworkDate DATETIME NOT NULL,
    PRIMARY KEY(idNetworkDevices)
);

CREATE TABLE drives(
    idDrives INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(22) NOT NULL,
    Vendor VARCHAR(22) NOT NULL,
    Device VARCHAR(22) NOT NULL,
    DeviceSize BIGINT NOT NULL,
	Free BIGINT NULL,
	Used BIGINT NULL,
	DriveDate DATETIME NOT NULL,
    PRIMARY KEY(idDrives)
);